routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/links/create', 'LinkController@create');
Route::post('/links/create', 'LinkController@store');
Route::resource('links', 'LinkController');
Route::get('logActivity', 'HomeController@logActivity');
Route::get('add-to-log', 'HomeController@myTestAddToLog');

app/Link.php
<?php

namespace App;


use Illuminate\Database\Eloquent\Model;

class Link extends Model
{
    protected $fillable = [
        'url'
    ];
    
    public function user()
    {
        return $this->belongsToMany(User::class, 'user_link');
    }
    
}

app/LogActivity.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class LogActivity extends Model
{
    protected $table = 'log_activity';
    protected $fillable = [
         'url', 'method', 'ip', 'agent','pays', 'user_id'
    ];
    public function user()
    {
        return $this->belongsToMany(User::class, 'log_activity','user_id');
    }
}

    

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function links()
{
  return $this->belongsToMany(Link::class,'user_link');
}
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;


use App\Link;
use App\Helpers\LogActivity;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
   

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $links=Link::all();
        return view('home',['links' => $links]);
    }
    


    public function logActivity()
    {
        $logs = LogActivity::logActivityLists();
        return view('logActivity',compact('logs'));
    }
}

app/Http/Controllers/LinkController.php
<?php

namespace App\Http\Controllers;

use App\Link;
use App\User;
use Carbon\Carbon;
use App\Helpers\LogActivity;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\RedirectResponse;


class LinkController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth', ['except' => ['show']]);
        $this->middleware('checkUserUrlNumber', ['only' => ['create','store']]);
    }
    public function index()
    {
        $user = User::find(Auth::id());
        $links = $user->links()->get();
        return view('links.index', ['links' => $links]);
    }
    public function create()
    {
       
        return view('links.create');
    }
    public function store(Request $request)
    {
        
        $request->validate([
            'url' => 'required'
        ]);
        if (Link::count() >= 20){Link::orderBy('id', 'asc')->limit(1)->delete();}
        
       
            $link = new Link;
        $link->url = $request->url;
        $link->save();

        $link->user()->attach(Auth::id());
        $link->save();
       
        return redirect('/links');
        
        
    }
    public function show(Link $link)
    {
        LogActivity::addToLog('');
        $link = Link::find($link)->first();
       
        return redirect($link->url, 301);
    }
    public function destroy(Link $link)
    {
        $link->user()->detach();
        $link->delete();
        
        return redirect('/links');
    }
}

resources/views/flash-message.blade.php
@if ($message = Session::get('success'))
<div class="alert alert-success alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>	
        <strong>{{ $message }}</strong>
</div>
@endif


@if ($message = Session::get('error'))
<div class="alert alert-danger alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>	
        <strong>{{ $message }}</strong>
</div>
@endif


@if ($message = Session::get('warning'))
<div class="alert alert-warning alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>	
	<strong>{{ $message }}</strong>
</div>
@endif


@if ($message = Session::get('info'))
<div class="alert alert-info alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>	
	<strong>{{ $message }}</strong>
</div>
@endif


@if ($errors->any())
<div class="alert alert-danger">
	<button type="button" class="close" data-dismiss="alert">×</button>	
	Please check the form below for errors
</div>
@endif

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('URL List') }}</div>

                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        @foreach ($links as $link)
                        <li class="list-group-item"><a href="{{ route('links.show', $link->id) }}">
                                {{ route('links.show', $link->id) }}
                            </a>
                        </li>
                        @endforeach
                    </ul>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
  <!-- Custom fonts for this template-->
  <link href="{{ asset('vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
@include('flash-message')
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                {{ __('TestBulldozer') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                    <a class="nav-link" href="{{ url('/home') }}">{{ __('Home') }}</a>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                        <li class="nav-item">
                                <a class="nav-link" href="{{ url('/logActivity') }}">{{ __('Log') }}</a>
                            </li>
                        <li class="nav-item">
                                <a class="nav-link" href="{{ url('/links') }}">{{ __('Your Links') }}</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/links/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Shorten a new link') }}</div>

                <div class="card-body">
                    <form action="" method="POST">
                        @csrf
                        <div class="form-group">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">    
                        <label for="url">{{ __('ENTER LONG URL') }}</label>
                            <input type="text" name="url" id="url" class="form-control" placeholder="https://...">

                        </div>
                        <div class="form-group">
                            <button class="btn btn-primary">{{ __('Create') }}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/links/index.blade.php
@extends('layouts.app')

@section('content')

<div class="row py-lg-2">
    <div class="col-md-6">
        <h2>{{ __('URL List') }}</h2>
    </div>
    <div class="col-md-6">
        <a href="{{ route('links.create') }}" class="btn btn-primary btn-lg float-md-right" role="button" aria-pressed="true">{{ __('Add New URL') }}</a>
    </div>
</div>

<!-- DataTables Example -->
<div class="card mb-3">


    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>{{ __('Link') }}</th>
                        <th>{{ __('Tools') }}</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>{{ __('Link') }}</th>
                        <th>{{ __('Tools') }}</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach ($links as $link)
                    <tr>
                        <td>
                            @csrf
                            <a href="{{ route('links.show', $link->id) }}">
                                {{ route('links.show', $link->id) }}
                            </a>
                        </td>
                        <td>
                            <form method="POST" action="{{ route('links.destroy', $link->id) }}">
                                @method('DELETE')
                                @csrf

                                <a class="btn btn-primary" onclick="$(this).closest('form').submit();">{{ __('Delete') }}</a>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
       
    </div>
</div>





@endsection

resources/views/logActivity.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<h1>{{ __('Log Activity') }}</h1>
	<table class="table table-bordered">
		<tr>
			<th>{{ __('No') }}</th>
			<th>{{ __('Access time') }}</th>
			<th>{{ __('URL') }}</th>
			<th>{{ __('User') }}</th>
			<th>{{ __('Ip') }}</th>
			<th>{{ __('Country') }}</th>
			<th width="300px">{{ __('User Agent') }}</th>
			
		</tr>
		@if($logs->count())
			@foreach($logs as $key => $log)
			<tr>
				<td>{{ ++$key }}</td>
				<td><label class="label label-info">{{ $log->created_at }}</label></td>
				<td class="text-success">{{ $log->url }}</td>
				<td>{{ $log->user_id }}</td>
				<td class="text-warning">{{ $log->ip }}</td>
				<td class="text-warning">{{ $log->pays }}</td>
				<td class="text-danger">{{ $log->agent }}</td>
				
				
			</tr>
			@endforeach
		@endif
	</table>
</div>

@endsection